### ISSUE TITLE
Handle Blender versions from 2.82

### ISSUE THREAD

**Issue by Krenodeno** [victorklos/ansible-role-install-blender#1]
The current ansible role does not handle newer versions 

### Current

Current supported URLs are in the form of  `release/Blender{{install_blender_version}}/blender-{{install_blender_version}}-linux-glibc{{install_blender_glibc_version}}-x86_64.tar.bz2`

### From Blender 2.82 onward, download URLs have lost their glibc part and switched to `.tar.xz` extension:
Example:
- https://download.blender.org/release/Blender2.82/blender-2.82-linux64.tar.xz

URL is in the form `release/Blender{{install_blender_version}}/blender-{{install_blender_version}}-linux64.tar.xz`

`install_blender_version` being in the form `2.79` but cannot include a suffix like `a`, `b` ...

### From Blender 2.83, they changed the version convention to include a third number, dropping the `a`, `b` ... suffixes:
Example:
- https://download.blender.org/release/Blender2.83/blender-2.83.0-linux64.tar.xz

URL is in the form `release/Blender{{install_blender_version}}/blender-{{install_blender_version_full}}-linux64.tar.xz`

- `install_blender_version` being in the major.minor format, e.g. `2.83`
- `install_blender_version_full` being in the major.minor.patch format, e.g. `2.83.0`

### From Blender 2.93, it changed again, adding a `-x`, going from `linux64` to `linux-x64`
Example:
- https://download.blender.org/release/Blender2.93/blender-2.93.0-linux-x64.tar.xz

URL is in the form `release/Blender{{install_blender_version}}/blender-{{install_blender_version_full}}-linux-x64.tar.xz`

- `install_blender_version` being in the major.minor format, e.g. `2.93`
- `install_blender_version_full` being in the major.minor.patch format, e.g. `2.93.0`

And this remain the same URL format as of today (current last version is 3.5.1).

---

Not sure how to handle all that logic, one could just drop support for versions older that `2.93.0`.

Let me now what you think about it.

**Comment by victorklos** [comment]
Thanks for reporting this!

Currently traveling, will think about it when I'm back. Your suggestion to drop support <2.93 makes most sense now, but we'll see.

**Comment by victorklos** [comment]
I have switched to NixOS and am no longer using Ansible. Are you still in need for this? Because then I will fix it, as a thank you for reporting.

**Comment by Krenodeno** [comment]
Hello, I'm trying to switch my workflow to docker, so I'm not in need of this fix. Thank you for reporting back :)

**Comment by victorklos** [comment]
Ok closing then
